FROM rasa/rasa-sdk:3.6.0
USER root
RUN adduser --disabled-password --gecos "" --uid 1001 action
COPY requirements.txt /app/requirements.txt
# Install the Python dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt
USER action
