services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile.rasa
    volumes:
      - ./app:/app
    environment:
     - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
     - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
    command: tail -f /dev/null
    #-  rasa run --enable-api --cors "*"
    networks:
      - rasa_network
    depends_on:
      - action_server
      - ngrok
    ports:
      - "5005:5005"

  action_server:
    build:
      context: .
      dockerfile: Dockerfile.action_server
    volumes:
      - ./app/actions:/app/actions
      - ./requirements.txt:/app/requirements.txt
    networks:
      - rasa_network
    ports:
      - "5055:5055"

  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    environment:
     - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: ngrok http rasa:5005
    networks:
      - rasa_network
    expose:
      - "4040"

networks:
  rasa_network:
    driver: bridge
